### ISSUE TITLE
Tracking issue for migrating to use `mlx-c`

### ISSUE THREAD

**Issue by minghuaw** [oxideai/mlx-rs#35]
- [ ] Document that `mlx` is lazy
- [ ] ~Perform type conversion for `as_slice`~ (Unlike `item()`, we cannot use `mlx_astype` on the inner pointer here because it creates a new `mlx_array` which should be freed at the end of this fn, making it the returned slice pointing at a temporary value.)
- [ ] Split `as_slice` into three versions
  - [ ] `as_slice<T>(&self) -> &[T]` - checks if the inner dtype is the same as the output dtype, panics if different. Also panics if pointer is null
  - [ ] `as_slice_unchecked<T>(&self) -> &[T]` - unsafe and does not perform any check
  - [ ] `try_as_slice<T>(&self) -> Result<&[T], Error>` - checks the type and returns an error if the types don't match or ptr is null
